### PR TITLE
Add a version to tag of `miplib-backends` image

### PR DESCRIPTION
**Pull request by nlordell**
This PR adds a new `version` file with a version that can be manually incremented in order to avoid issues where updating the SCIP or Gurobi version breaks compatibility with `miplib` versions.

Note that the `version` file **does not need to be changed** when updating SCIP and Gurobi versions that do not cause breaking changes with the `miplib` C++ code.

### Test Plan

Some echo-debugging ;)

<details><summary>Apply the following patch</summary>

```diff
diff --git a/docker/deploy.sh b/docker/deploy.sh
index 45267d9..ee47740 100755
--- a/docker/deploy.sh
+++ b/docker/deploy.sh
@@ -10,14 +10,14 @@ fi
 tag="$DOCKERHUB_PROJECT:$label"
 
 # Build and tag image
-docker build --pull -t $tag -f docker/Dockerfile .
-docker push $tag
+echo docker build --pull -t $tag -f docker/Dockerfile .
+echo docker push $tag
 
 # additionally, tag the image with the version in `docker/version` file if the
 # deployment is not for a build triggered by a tag. This prevents issues with
 # breaking compatibility when updating the SCIP and Gurobi versions.
 if [[ "${GITHUB_REF:-}" != refs/tags/* ]]; then
     full_tag="$DOCKERHUB_PROJECT:$(cat docker/version)-$label"
-    docker tag $tag $full_tag
-    docker push $full_tag
+    echo docker tag $tag $full_tag
+    echo docker push $full_tag
 fi
 ```
 
 </details>
 
 Then run:
```
$ # Running without `GITHUB_REF` defaults to `latest`
$ DOCKERHUB_PROJECT=foo/bar docker/deploy.sh
docker build --pull -t foo/bar:latest -f docker/Dockerfile .
docker push foo/bar:latest
docker tag foo/bar:latest foo/bar:1-latest
docker push foo/bar:1-latest
$ # Uses branch name when building GitHub action manually or on a schedule
$ DOCKERHUB_PROJECT=foo/bar GITHUB_REF=refs/heads/main docker/deploy.sh
docker build --pull -t foo/bar:main -f docker/Dockerfile .
docker push foo/bar:main
docker tag foo/bar:latest foo/bar:1-main
docker push foo/bar:1-main
$ # For tagged builds, only pushes a single tag
$ DOCKERHUB_PROJECT=foo/bar GITHUB_REF=refs/tags/v1 docker/deploy.sh
docker build --pull -t foo/bar:v1 -f docker/Dockerfile .
docker push foo/bar:v1
```

### CODE REVIEW

**Review by marcovc — APPROVED** [review]
LGTM. Just a question regarding:

> Note that the version file does not need to be changed when updating SCIP and Gurobi versions that do not cause breaking changes with the miplib C++ code.

My understanding is that if the version file is not bumped then the miplib and other clients of this docker image won't benefit from the improvements in the new SCIP/Gurobi versions as well (even if there are no breaking changes). Right?

**Comment by nlordell** [comment]
> My understanding is that if the version file is not bumped then the miplib and other clients of this docker image won't benefit from the improvements in the new SCIP/Gurobi versions as well (even if there are no breaking changes). Right?

If you bump the SCIP and Gurobi versions, and there are no breaking changes, then there is no need to bump the value in the version file. Once a new image is built (either manually, or on a schedule), then the next time Quasimodo (or other clients that also ensure to pull the latest version of the image - we use `--pull` flag to ensure this happens in Quasimodo) they will also use the latest version of this image (since we update the tag to a newer version).

**Comment by marcovc** [comment]
Thanks, but to be on the safe side, what is the drawback of just bumping the version file every time SCIP or Gurobi version changes?

**Comment by nlordell** [comment]
> but to be on the safe side, what is the drawback of just bumping the version file every time SCIP or Gurobi version changes?

None, just more maintenance work on Quasimodo side.

**Comment by marcovc** [comment]
Got it now - you were concerned that miplib could be used from clients other than quasimodo.

**Pull request merged**
